- name: Deploy to Cloud Run
  run: |
    gcloud run deploy glysthealth-service \
      --image=gcr.io/$PROJECT_ID/glysthealth-wordpress \
      --region=us-central1 \
      --platform=managed \
      --allow-unauthenticated
